import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import AppProviders from "@/components/AppProviders";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <AppProviders>
        <body>{children}</body>
      </AppProviders>
    </html>
  );
}
